#!/usr/bin/env python

import gc, untwisted, weakref
from testify import *

class outer:
  class inner:
    class __metaclass__(type):
      __get__ = untwisted.ctxual

sample = outer()

equal(sample, sample.inner.ctx)
equal(sample.inner, sample.inner)

a = outer()
b = outer()

ok(b.inner is not a.inner)

class outer:
  class a:
    class __metaclass__(type):
      __get__ = untwisted.ctxual

  class b:
    class __metaclass__(type):
      __get__ = untwisted.ctxual

sample = outer()

ok(sample.b is not sample.a)

@test
def finalInstance():
  expect(1)

  class outer:
    class inner:
      class __metaclass__(type):
        __get__ = untwisted.ctxual

  sample = outer()

  ref = weakref.ref(sample.inner, untwisted.partial(ok, True))

  del sample

  gc.collect()

@test
def finalCtx():
  expect(1)

  class outer:
    class inner:
      class __metaclass__(type):
        __get__ = untwisted.ctxual

  sample = outer()

  ref = weakref.ref(sample.inner, untwisted.partial(ok, True))

  del outer.inner

  gc.collect()

@test
def cycleInstance():
  expect(1)

  class outer:
    class inner:
      class __metaclass__(type):
        __get__ = untwisted.ctxual

  sample = outer()
  sample.cycle = sample.inner

  ref = weakref.ref(sample.inner, untwisted.partial(ok, True))

  del sample

  gc.collect()

@test
def cycleCtx():
  expect(1)

  class outer:
    class inner:
      class __metaclass__(type):
        __get__ = untwisted.ctxual

  sample = outer()
  outer.__dict__['inner'].cycle = sample.inner

  ref = weakref.ref(sample.inner, untwisted.partial(ok, True))

  del outer.inner

  gc.collect()
