#!/usr/bin/env python

from testify import *
from untwisted import db

expect(2)

class module:

  @staticmethod
  def connect(*args, **kwds):
    equal(('First', 'Second', 'Third'), args)
    equal({ 'First': 'Tsrif', 'Second': 'Dnoces', 'Third': 'Driht', 'module': module }, kwds)

db.connect('First', 'Second', 'Third', First='Tsrif', Second='Dnoces', Third='Driht', module=module)
