#!/usr/bin/env python

import untwisted
from testify import *
from untwisted import dns, promise, tcp

@test
def lookup():
  expect(2)

  class transport:
    class protocol:
      dataReceived = promise.sequence()

    write = promise.sequence()

  connect = tcp.connect
  tcp.connect = lambda host, port: lambda: transport

  try:
    dns.lookup('example.com').then(untwisted.partial(equal, '1.2.3.4'))

  finally:
    tcp.connect = connect

  transport.write.shift().then(untwisted.partial(equal, '\0\x1d\0\0\1\0\0\1\0\0\0\0\0\0\7example\3com\0\0\1\0\1'))

  transport.protocol.dataReceived('\0\x38\0\0\x81\x80\0\1\0\1\0\0\0\0\7example\3com\0\0\1\0\1\7example\3com\0\0\1\0\1\0\0\0\0\0\4\1\2\3\4')

@test
def compress():
  expect(2)

  class transport:
    class protocol:
      dataReceived = promise.sequence()

    write = promise.sequence()

  connect = tcp.connect
  tcp.connect = lambda host, port: lambda: transport

  try:
    dns.lookup('example.com').then(untwisted.partial(equal, '1.2.3.4'))

  finally:
    tcp.connect = connect

  transport.write.shift().then(untwisted.partial(equal, '\0\x1d\0\0\1\0\0\1\0\0\0\0\0\0\7example\3com\0\0\1\0\1'))

  transport.protocol.dataReceived('\0\x2d\0\0\x81\x80\0\1\0\1\0\0\0\0\7example\3com\0\0\1\0\1\xc0\x0c\0\1\0\1\0\0\0\0\0\4\1\2\3\4')
