#!/usr/bin/env python

from testify import *
from untwisted import event

sample = event.Event()
equal(sample('Call'), sample)

try:
  sample.throw('Throw')

  ok(False)

except StopIteration:
  pass

sample = event.Event()
equal(sample.connect('Connect'), sample)

sample = event.Event()
equal(sample.throw('Throw'), sample)

try:
  sample('Call')

  ok(False)

except StopIteration:
  pass

@event.connect
def connectThenCall():
  expect(1)

  equal(('Connect then call',), (yield event.Event()))

test(lambda: connectThenCall()('Connect then call'))

@test
@event.connect
def callThenConnect():
  expect(1)

  sample = event.Event()
  sample('Call then connect')
  equal(('Call then connect',), (yield sample))

@event.connect
def connectThenThrow():
  expect(1)

  try:
    yield event.Event()

    ok(False)

  except:
    ok(True)

test(lambda: connectThenThrow().throw(Exception))

@test
@event.connect
def throwThenConnect():
  expect(1)

  sample = event.Event()
  sample.throw(Exception)

  try:
    yield sample

    ok(False)

  except:
    ok(True)

@test
@event.connect
def callThenShift():
  expect(1)

  sample = event.Sequence()
  sample('Call then shift')
  equal(('Call then shift',), (yield sample.shift()))

@event.connect
def shiftThenCall():
  expect(1)

  equal(('Shift then call',), (yield event.Sequence().shift()))

test(lambda: shiftThenCall()('Shift then call'))
