#!/usr/bin/env python

import gc, untwisted
from testify import *

@test
def noReference():
  expect(1)

  untwisted.final(lambda: ok(True))

@test
def collectableCycle():
  expect(1)

  sample = untwisted.final(lambda: ok(True))
  sample.cycle = sample

  del sample

  gc.collect()

# Cancel

untwisted.final(lambda: ok(False)).cancel()
