#!/usr/bin/env python

from testify import *
from untwisted import smtp

sample = smtp.reply(123, 'first', 'second', 'third')
equal(int(sample), 123)
equal(str(sample), '123-first\r\n123-second\r\n123 third\r\n')

sample = smtp.command('VERB')
equal(sample.verb, 'VERB')
equal(str(sample), 'VERB\r\n')

sample = smtp.command('VERB text')
equal(sample.verb, 'VERB')
equal(str(sample), 'VERB text\r\n')

sample = smtp.command('VERB', 'text')
equal(sample.verb, 'VERB')
equal(str(sample), 'VERB text\r\n')
