#!/usr/bin/env python

import os, untwisted
from testify import *
from untwisted import promise, stun, udp

@test
def request():
  expect(7)

  class transport:
    recv = promise.sequence().shift
    write = promise.sequence()

  def callback(actual):
    equal(stun.binding, actual.messageMethod)
    equal(0x0100, actual.messageClass)

    equal('\x21\x12\xa4\x42', actual.magicCookie)
    equal('abcdefghijkl', actual.transactionId)

    (type, value), = actual.attribute

    equal(stun.MAPPED_ADDRESS, type)
    equal('\0\1\xab\xcd\1\2\3\4', value.value)

  connect = udp.connect
  urandom = os.urandom

  udp.connect, os.urandom = lambda host, port: lambda: transport, lambda _: 'abcdefghijkl'

  try:
    stun.request('example.com').then(callback)

  finally:
    udp.connect = connect
    os.urandom = urandom

  transport.write.shift().then(untwisted.partial(equal, '\0\1\0\0\x21\x12\xa4\x42abcdefghijkl'))

  transport.recv.__self__('\1\1\0\x0c\x21\x12\xa4\x42abcdefghijkl\0\1\0\x08\0\1\xab\xcd\1\2\3\4')

@test
def mappedAddress():
  expect(4)

  class transport:
    recv = promise.sequence().shift
    write = promise.sequence()

  def callback(actual):
    (_, value), = actual.attribute

    equal(stun.IPv4, value.family)
    equal(0xabcd, value.port)
    equal('1.2.3.4', value.address)

  connect = udp.connect
  urandom = os.urandom

  udp.connect, os.urandom = lambda host, port: lambda: transport, lambda _: 'abcdefghijkl'

  try:
    stun.request('example.com').then(callback)

  finally:
    udp.connect = connect
    os.urandom = urandom

  transport.write.shift().then(untwisted.partial(equal, '\0\1\0\0\x21\x12\xa4\x42abcdefghijkl'))

  transport.recv.__self__('\1\1\0\x0c\x21\x12\xa4\x42abcdefghijkl\0\1\0\x08\0\1\xab\xcd\1\2\3\4')

@test
def xorMappedAddress():
  expect(4)

  class transport:
    recv = promise.sequence().shift
    write = promise.sequence()

  def callback(actual):
    (_, value), = actual.attribute

    equal(stun.IPv4, value.family)
    equal(0xabcd, value.port)
    equal('1.2.3.4', value.address)

  connect = udp.connect
  urandom = os.urandom

  udp.connect, os.urandom = lambda host, port: lambda: transport, lambda _: 'abcdefghijkl'

  try:
    stun.request('example.com').then(callback)

  finally:
    udp.connect = connect
    os.urandom = urandom

  transport.write.shift().then(untwisted.partial(equal, '\0\1\0\0\x21\x12\xa4\x42abcdefghijkl'))

  transport.recv.__self__('\1\1\0\x0c\x21\x12\xa4\x42abcdefghijkl\0\x20\0\x08\0\1\x8a\xdf\x20\x10\xa7\x46')

@test
def errorResponse():
  expect(7)

  class transport:
    recv = promise.sequence().shift
    write = promise.sequence()

  class callback:

    @staticmethod
    def throw(type, value, traceback):
      equal(stun.binding, value.messageMethod)
      equal(0x0110, value.messageClass)

      equal('\x21\x12\xa4\x42', value.magicCookie)
      equal('abcdefghijkl', value.transactionId)

      (type, value), = value.attribute

      equal(stun.ERROR_CODE, type)
      equal('\0\0\5\x43Expect', value.value)

  connect = udp.connect
  urandom = os.urandom

  udp.connect, os.urandom = lambda host, port: lambda: transport, lambda _: 'abcdefghijkl'

  try:
    stun.request('example.com').then(callback)

  finally:
    udp.connect = connect
    os.urandom = urandom

  transport.write.shift().then(untwisted.partial(equal, '\0\1\0\0\x21\x12\xa4\x42abcdefghijkl'))

  transport.recv.__self__('\1\x11\0\x10\x21\x12\xa4\x42abcdefghijkl\0\x09\0\x0a\0\0\5\x43Expect\0\0')

@test
def errorCode():
  expect(4)

  class transport:
    recv = promise.sequence().shift
    write = promise.sequence()

  class callback:

    @staticmethod
    def throw(type, value, traceback):
      (_, value), = value.attribute

      equal(5, value['class'])
      equal(67, value.number)
      equal('Expect', value.reasonPhrase)

  connect = udp.connect
  urandom = os.urandom

  udp.connect, os.urandom = lambda host, port: lambda: transport, lambda _: 'abcdefghijkl'

  try:
    stun.request('example.com').then(callback)

  finally:
    udp.connect = connect
    os.urandom = urandom

  transport.write.shift().then(untwisted.partial(equal, '\0\1\0\0\x21\x12\xa4\x42abcdefghijkl'))

  transport.recv.__self__('\1\x11\0\x10\x21\x12\xa4\x42abcdefghijkl\0\x09\0\x0a\0\0\5\x43Expect\0\0')

@test
def unknownAttributes():
  expect(2)

  class transport:
    recv = promise.sequence().shift
    write = promise.sequence()

  class callback:

    @staticmethod
    def throw(type, value, traceback):
      (_, value), = value.attribute

      equal((1, 2, 3), tuple(value.attributeType))

  connect = udp.connect
  urandom = os.urandom

  udp.connect, os.urandom = lambda host, port: lambda: transport, lambda _: 'abcdefghijkl'

  try:
    stun.request('example.com').then(callback)

  finally:
    udp.connect = connect
    os.urandom = urandom

  transport.write.shift().then(untwisted.partial(equal, '\0\1\0\0\x21\x12\xa4\x42abcdefghijkl'))

  transport.recv.__self__('\1\x11\0\x0c\x21\x12\xa4\x42abcdefghijkl\0\x0a\0\6\0\1\0\2\0\3\0\0')

@test
def alternateServer():
  expect(4)

  class transport:
    recv = promise.sequence().shift
    write = promise.sequence()

  class callback:

    @staticmethod
    def throw(type, value, traceback):
      (_, value), = value.attribute

      equal(stun.IPv4, value.family)
      equal(0xabcd, value.port)
      equal('1.2.3.4', value.address)

  connect = udp.connect
  urandom = os.urandom

  udp.connect, os.urandom = lambda host, port: lambda: transport, lambda _: 'abcdefghijkl'

  try:
    stun.request('example.com').then(callback)

  finally:
    udp.connect = connect
    os.urandom = urandom

  transport.write.shift().then(untwisted.partial(equal, '\0\1\0\0\x21\x12\xa4\x42abcdefghijkl'))

  transport.recv.__self__('\1\x11\0\x0c\x21\x12\xa4\x42abcdefghijkl\x80\x23\0\x08\0\1\xab\xcd\1\2\3\4')

@test
def many():
  expect(5)

  class transport:
    recv = promise.sequence().shift
    write = promise.sequence()

  def callback(actual):
    a, b = actual.attribute

    type, value = a

    equal(stun.MAPPED_ADDRESS, type)
    equal('\0\1\xab\xcd\1\2\3\4', value.value)

    type, value = b

    equal(stun.SOFTWARE, type)
    equal('Expect', value.value)

  connect = udp.connect
  urandom = os.urandom

  udp.connect, os.urandom = lambda host, port: lambda: transport, lambda _: 'abcdefghijkl'

  try:
    stun.request('example.com').then(callback)

  finally:
    udp.connect = connect
    os.urandom = urandom

  transport.write.shift().then(untwisted.partial(equal, '\0\1\0\0\x21\x12\xa4\x42abcdefghijkl'))

  transport.recv.__self__('\1\1\0\x18\x21\x12\xa4\x42abcdefghijkl\0\1\0\x08\0\1\xab\xcd\1\2\3\4\x80\x22\0\6Expect\0\0')
