import rfc3966, rfc5234
from qwer import *

alphanum = qwer('(?:', rule('rfc5234.ALPHA'), '|', rule('rfc5234.DIGIT'), ')')
mark = qwer('[!\'()*\-._~]')
unreserved = qwer('(?:', rule('alphanum'), '|', rule('mark'), ')')
escaped = qwer('%', rule('rfc5234.HEXDIG'), rule('rfc5234.HEXDIG'))
userUnreserved = qwer('[$&+,/;=?]')
user = qwer('(?:', rule('unreserved'), '|', rule('escaped'), '|', rule('userUnreserved'), ')+')
password = qwer('(?:', rule('unreserved'), '|', rule('escaped'), '|[$&+,=])*')
userinfo = qwer('(?:', rule('user'), '|', rule('rfc3966.telephoneSubscriber'), ')(?::', rule('password'), ')?@')
domainlabel = qwer('(?:', rule('alphanum'), '|', rule('alphanum'), '(?:', rule('alphanum'), '|-)*', rule('alphanum'), ')')
toplabel = qwer('(?:', rule('rfc5234.ALPHA'), '|', rule('rfc5234.ALPHA'), '(?:', rule('alphanum'), '|-)*', rule('alphanum'), ')')
hostname = qwer('(?:', rule('domainlabel'), '\.)*', rule('toplabel'), '\.?')
hex4 = qwer('(?:', rule('rfc5234.HEXDIG'), '){1,4}')
hexseq = qwer(rule('hex4'), '(?::', rule('hex4'), ')*')
hexpart = qwer('(?:', rule('hexseq'), '|', rule('hexseq'), '::(?:', rule('hexseq'), ')?|::(?:', rule('hexseq'), ')?)')
ipv4address = qwer('(?:', rule('rfc5234.DIGIT'), '){1,3}\.(?:', rule('rfc5234.DIGIT'), '){1,3}\.(?:', rule('rfc5234.DIGIT'), '){1,3}\.(?:', rule('rfc5234.DIGIT'), '){1,3}')
ipv6address = qwer(rule('hexpart'), '(?::', rule('ipv4address'), ')?')
ipv6reference = qwer('\[', rule('ipv6address'), ']')
host = qwer('(?:', rule('hostname'), '|', rule('ipv4address'), '|', rule('ipv6reference'), ')')
port = qwer('(?:', rule('rfc5234.DIGIT'), ')+')
hostport = qwer(rule('host'), '(?::', rule('port'), ')?')
token = qwer('(?:', rule('alphanum'), '|[-!%*+\'._`~])+')
otherTransport = rule('token')
transportParam = qwer('transport=(?:udp|tcp|sctp|tls|', rule('otherTransport'), ')')
otherUser = rule('token')
userParam = qwer('user=(?:phone|ip|', rule('otherUser'), ')')
extensionMethod = rule('token')
method = qwer('(?:INVITE|ACK|OPTIONS|BYE|CANCEL|REGISTER|', rule('extensionMethod'), ')')
methodParam = qwer('method=', rule('method'))

# 0 to 255
ttl = qwer('(?:', rule('rfc5234.DIGIT'), '){1,3}')

ttlParam = qwer('ttl=', rule('ttl'))
maddrParam = qwer('maddr=', rule('host'))
lrParam = qwer('lr')
paramUnreserved = qwer('[]$&+/:[]')
paramchar = qwer('(?:', rule('paramUnreserved'), '|', rule('unreserved'), '|', rule('escaped'), ')')
pname = qwer('(?:', rule('paramchar'), ')+')
pvalue = qwer('(?:', rule('paramchar'), ')+')
otherParam = qwer(rule('pname'), '(?:=', rule('pvalue'), ')?')
uriParameter = qwer('(?:', rule('transportParam'), '|', rule('userParam'), '|', rule('methodParam'), '|', rule('ttlParam'), '|', rule('maddrParam'), '|', rule('lrParam'), '|', rule('otherParam'), ')')
uriParameters = qwer('(?:;', rule('uriParameter'), ')*')
hnvUnreserved = qwer('[]$+/:?[]')
hvalue = qwer('(?:', rule('hnvUnreserved'), '|', rule('unreserved'), '|', rule('escaped'), ')*')
hname = qwer('(?:', rule('hnvUnreserved'), '|', rule('unreserved'), '|', rule('escaped'), ')+')
header = qwer(rule('hname'), '=', rule('hvalue'))
headers = qwer('\?', rule('header'), '(?:&', rule('header'), ')*')
sipUri = qwer('sip:(?:', rule('userinfo'), ')?', rule('hostport'), rule('uriParameters'), '(?:', rule('headers'), ')?')
sipsUri = qwer('sips:(?:', rule('userinfo'), ')?', rule('hostport'), rule('uriParameters'), '(?:', rule('headers'), ')?')
scheme = qwer(rule('rfc5234.ALPHA'), '(?:', rule('rfc5234.ALPHA'), '|', rule('rfc5234.DIGIT'), '|[-+.])*')
srvr = qwer('(?:(?:', rule('userinfo'), '@)?', rule('hostport'), ')?')
regName = qwer('(?:', rule('unreserved'), '|', rule('escaped'), '|[$&+,:;=@])+')
authority = qwer('(?:', rule('srvr'), '|', rule('regName'), ')')
pchar = qwer('(?:', rule('unreserved'), '|', rule('escaped'), '|[$&+,:=@])')
param = qwer('(?:', rule('pchar'), ')*')
segment = qwer('(?:', rule('pchar'), ')*(?:;', rule('param'), ')*')
pathSegments = qwer(rule('segment'), '(?:/', rule('segment'), ')*')
absPath = qwer('/', rule('pathSegments'))
netPath = qwer('//', rule('authority'), '(?:', rule('absPath'), ')?')
reserved = qwer('[$&+,/:;=?@]')
uric = qwer('(?:', rule('reserved'), '|', rule('unreserved'), '|', rule('escaped'), ')')
query = qwer('(?:', rule('uric'), ')*')
hierPart = qwer('(?:', rule('netPath'), '|', rule('absPath'), ')(?:\?', rule('query'), ')?')
uricNoSlash = qwer('(?:', rule('unreserved'), '|', rule('escaped'), '|[$&+,:;=?@])')
opaquePart = qwer(rule('uricNoSlash'), '(?:', rule('uric'), ')*')
absoluteUri = qwer(rule('scheme'), ':(?:', rule('hierPart'), '|', rule('opaquePart'), ')')
requestUri = qwer('(?:', rule('sipUri'), '|', rule('sipsUri'), '|', rule('absoluteUri'), ')')
