#!/usr/bin/env python

import untwisted
from testify import *
from untwisted import promise

@test
def join():
  expect(1)

  sample = promise.join()
  sample(promise.promise()('Expect'))

  sample.then(untwisted.partial(equal, 'Expect'))

@test
def joinNonPromise():
  expect(1)

  sample = promise.join()
  sample('Expect')

  sample.then(untwisted.partial(equal, 'Expect'))
