#!/usr/bin/env python

import untwisted
from testify import *
from untwisted import promise

@test
def now():
  expect(1)

  sample = promise.promise()
  sample('Expect')

  promise.nowThen(sample,
    untwisted.partial(equal, 'Expect'),
    untwisted.partial(ok, False))

@test
def then():
  expect(1)

  sample = promise.promise()

  promise.nowThen(sample,
    untwisted.partial(ok, False),
    untwisted.partial(equal, 'Expect'))

  sample('Expect')

def noNow():
  expect(1)

  sample = promise.promise()
  sample('Expect')
  promise.nowThen(sample)

  sample.then(untwisted.partial(equal, 'Expect'))

test(noNow)
test(noNow)

def noThen():
  expect(1)

  sample = promise.promise()
  promise.nowThen(sample)
  sample('Expect')

  sample.then(untwisted.partial(equal, 'Expect'))

test(noThen)
test(noThen)
