#!/usr/bin/env python

import functools, untwisted
from testify import *
from untwisted import promise

@test
def callThenShift():
  expect(1)

  sample = promise.sequence()
  sample('Expect')

  sample.shift().then(functools.partial(equal, 'Expect'))

@test
def shiftThenCall():
  expect(1)

  sample = promise.sequence()

  sample.shift().then(functools.partial(equal, 'Expect'))

  sample('Expect')
