#!/usr/bin/env python

import untwisted
from testify import *
from untwisted import event, smtp

@test
@event.continuate
def data():
  expect(2)

  class transport:
    class protocol:
      dataReceived = event.sequence()

    write = event.sequence()

  client = type.__call__(smtp.client, transport)
  sample = type.__call__(client.mail)
  sample.dataCmd('Expect')

  equal('DATA\r\n', (yield transport.write.shift()))

  transport.protocol.dataReceived('354\r\n')

  equal('Expect\r\n.\r\n', (yield transport.write.shift()))

@test
@event.continuate
def dataCrlf():
  expect(2)

  class transport:
    class protocol:
      dataReceived = event.sequence()

    write = event.sequence()

  client = type.__call__(smtp.client, transport)
  sample = type.__call__(client.mail)
  sample.dataCmd('Expect\r\n')

  equal('DATA\r\n', (yield transport.write.shift()))

  transport.protocol.dataReceived('354\r\n')

  equal('Expect\r\n.\r\n', (yield transport.write.shift()))

@test
@event.continuate
def reply():
  expect(1)

  class transport:
    class protocol:
      dataReceived = event.sequence()

    write = event.sequence()

  client = type.__call__(smtp.client, transport)
  client.reply(untwisted.wildcard)
  transport.protocol.dataReceived('456 Ignore\r\n234 Expect\r\n')

  equal('234 Expect\r\n', str((yield client.reply())))
