#!/usr/bin/env python

import functools, re, untwisted
from testify import *
from untwisted import promise, rfc5234, rfc5321, smtp

@test
@promise.continuate
def receive():
  expect(11)

  class server(smtp.server):

    @untwisted.each
    def mail():
      class sample(smtp.server.mail):
        mail = staticmethod(untwisted.each(lambda: equal('alice@example.com', (yield))))

        recipient = staticmethod(untwisted.each(lambda: equal('bob@example.com', (yield))))

        data = staticmethod(untwisted.each(lambda: equal('Expect', (yield))))

      # QUIT
      yield smtp.server.mail.__get__((yield sample.__get__((yield))()))()

  class transport:
    loseConnection = functools.partial(ok, True)

    class protocol:
      dataReceived = promise.sequence()

    write = promise.sequence()

  server(transport)

  actual = yield transport.write.shift()
  ok(re.match('(?:220-(?:' + rfc5321.textstring + ')?' + rfc5234.CRLF + ')*220(?: ' + rfc5321.textstring + ')?' + rfc5234.CRLF, actual), actual)

  transport.protocol.dataReceived('EHLO example.com\r\n')

  actual = yield transport.write.shift()
  ok(re.match('(?:250-(?:' + rfc5321.textstring + ')?' + rfc5234.CRLF + ')*250(?: ' + rfc5321.textstring + ')?' + rfc5234.CRLF, actual), actual)

  transport.protocol.dataReceived('MAIL FROM:<alice@example.com>\r\n')

  equal('250 Requested mail action okay, completed\r\n', (yield transport.write.shift()))

  transport.protocol.dataReceived('RCPT TO:<bob@example.com>\r\n')

  equal('250 Requested mail action okay, completed\r\n', (yield transport.write.shift()))

  transport.protocol.dataReceived('DATA\r\n')

  equal('354 Start mail input; end with <CRLF>.<CRLF>\r\n', (yield transport.write.shift()))

  transport.protocol.dataReceived('Expect\r\n.\r\n')

  equal('250 Requested mail action okay, completed\r\n', (yield transport.write.shift()))

  transport.protocol.dataReceived('QUIT\r\n')

  equal('221 Service closing transmission channel\r\n', (yield transport.write.shift()))
