#!/usr/bin/env python

import functools, re, untwisted
from testify import *
from untwisted import event, rfc5321, smtp

def nowThen(result, now=lambda *args, **kwds: event.event()(*args, **kwds), then=lambda *args, **kwds: event.event()(*args, **kwds)):
  wrapper = lambda *args, **kwds: callback(*args, **kwds)

  callback = now
  try:
    wrapper.throw = now.throw

  except AttributeError:
    pass

  try:
    return result.connect(wrapper)

  finally:
    callback = then
    try:
      wrapper.throw = then.throw

    except AttributeError:
      try:
        del wrapper.throw

      except AttributeError:
        pass

@test
def send():
  expect(6)

  class client(smtp.client):

    @untwisted.each
    def mail():
      class sample(smtp.client.mail):
        mail = iter(('alice@example.com',)).next

        recipient = iter(('bob@example.com',)).next

        data = iter(('Expect',)).next

      yield sample.__get__((yield))()

  class transport:
    class protocol:
      dataReceived = event.sequence()

    write = event.sequence()

  client(transport)

  nowThen(transport.write.shift(),
    functools.partial(ok, False),
    lambda actual: ok(re.match(rfc5321.ehlo, actual), actual))

  transport.protocol.dataReceived('220\r\n')

  nowThen(transport.write.shift(),
    functools.partial(ok, False),
    functools.partial(equal, 'MAIL FROM:<alice@example.com>\r\n'))

  transport.protocol.dataReceived('250\r\n')

  nowThen(transport.write.shift(),
    functools.partial(ok, False),
    functools.partial(equal, 'RCPT TO:<bob@example.com>\r\n'))

  transport.protocol.dataReceived('250\r\n')

  nowThen(transport.write.shift(),
    functools.partial(ok, False),
    functools.partial(equal, 'DATA\r\n'))

  transport.protocol.dataReceived('250\r\n')

  nowThen(transport.write.shift(),
    functools.partial(ok, False),
    functools.partial(equal, 'Expect\r\n.\r\n'))

  transport.protocol.dataReceived('354\r\n')

  nowThen(transport.write.shift(),
    functools.partial(ok, False),
    functools.partial(equal, 'QUIT\r\n'))

  transport.protocol.dataReceived('250\r\n')

  transport.protocol.dataReceived('221\r\n')
