#!/usr/bin/env python

import functools, re, untwisted
from testify import *
from untwisted import event, rfc5321, smtp

@test
def send():
  expect(6)

  class client(smtp.client):

    @untwisted.each
    def mail():
      class sample(smtp.client.mail):
        mail = iter(('alice@example.com',)).next

        recipient = iter(('bob@example.com',)).next

        data = iter(('Expect',)).next

      yield sample.__get__((yield))()

  class transport:
    class protocol:
      dataReceived = event.sequence()

    write = event.sequence()

  client(transport)

  callback = functools.partial(ok, False)
  transport.write.shift().connect(lambda actual: callback(actual))

  callback = lambda actual: ok(re.match(rfc5321.ehlo, actual), actual)
  transport.protocol.dataReceived('220\r\n')

  callback = functools.partial(ok, False)
  transport.write.shift().connect(lambda actual: callback(actual))

  callback = lambda actual: equal(actual, 'MAIL FROM:<alice@example.com>\r\n')
  transport.protocol.dataReceived('250\r\n')

  callback = functools.partial(ok, False)
  transport.write.shift().connect(lambda actual: callback(actual))

  callback = lambda actual: equal(actual, 'RCPT TO:<bob@example.com>\r\n')
  transport.protocol.dataReceived('250\r\n')

  callback = functools.partial(ok, False)
  transport.write.shift().connect(lambda actual: callback(actual))

  callback = lambda actual: equal(actual, 'DATA\r\n')
  transport.protocol.dataReceived('250\r\n')

  callback = functools.partial(ok, False)
  transport.write.shift().connect(lambda actual: callback(actual))

  callback = lambda actual: equal(actual, 'Expect\r\n.\r\n')
  transport.protocol.dataReceived('354\r\n')

  callback = functools.partial(ok, False)
  transport.write.shift().connect(lambda actual: callback(actual))

  callback = lambda actual: equal(actual, 'QUIT\r\n')
  transport.protocol.dataReceived('250\r\n')

  transport.protocol.dataReceived('221\r\n')
