#!/usr/bin/env python

from testify import *
from untwisted import promise, smtp

@test
@promise.continuate
def command():
  expect(1)

  class transport:
    class protocol:
      dataReceived = promise.sequence()

    write = promise.sequence()

  server = type.__call__(smtp.server, transport)
  server.command()
  transport.protocol.dataReceived('IGNORE\r\nEXPECT\r\n')

  equal('EXPECT\r\n', str((yield server.command())))
