#!/usr/bin/env python

from testify import *
from untwisted import smtp

sample = smtp.reply(123, 'First', 'Second', 'Third')

equal(int(sample), 123)
equal(str(sample), '123-First\r\n123-Second\r\n123 Third\r\n')

sample = smtp.command('VERB')

equal(sample.verb, 'VERB')
equal(str(sample), 'VERB\r\n')

sample = smtp.command('VERB Text')

equal(sample.verb, 'VERB')
equal(str(sample), 'VERB Text\r\n')

sample = smtp.command('VERB', 'Text')

equal(sample.verb, 'VERB')
equal(str(sample), 'VERB Text\r\n')
