#!/usr/bin/env python

import functools
from testify import *
from untwisted import event

@test
def join():
  expect(1)

  sample = event.join()
  sample(event.event()('Expect'))

  sample.connect(functools.partial(equal, 'Expect'))

@test
def joinNonEvent():
  expect(1)

  sample = event.join()
  sample('Expect')

  sample.connect(functools.partial(equal, 'Expect'))
