#!/usr/bin/env python

import untwisted
from testify import *
from untwisted import event

@test
def callThenShift():
  expect(1)

  sample = event.sequence()
  sample('Expect')

  sample.shift().connect(lambda actual: equal(actual, 'Expect'))

@test
def shiftThenCall():
  expect(1)

  sample = event.sequence()

  sample.shift().connect(lambda actual: equal(actual, 'Expect'))

  sample('Expect')
