#!/usr/bin/env python

import sys
from testify import *
from untwisted import event

@test
def propagate():
  expect(1)

  sample = event.event()
  for ignore in range(sys.getrecursionlimit()):
    sample.connect(lambda count: count + 1)

  sample(0)

  sample.connect(lambda actual: equal(actual, sys.getrecursionlimit()))

@test
def propagageAndConnect():
  expect(1)

  sample = event.event()

  def callback(count):
    if sys.getrecursionlimit() > count + 1:
      sample.connect(callback)

    return count + 1

  sample.connect(callback)(0)

  sample.connect(lambda actual: equal(actual, sys.getrecursionlimit()))
