#!/usr/bin/env python

import functools, sys
from testify import *
from untwisted import event

@test
def propagate():
  expect(1)

  sample = event.event()
  for _ in range(sys.getrecursionlimit()):
    sample.connect(lambda count: count + 1)

  sample(0)

  sample.connect(functools.partial(equal, sys.getrecursionlimit()))

@test
def propagageAndConnect():
  expect(1)

  sample = event.event()

  def callback(count):
    if sys.getrecursionlimit() > count + 1:
      sample.connect(callback)

    return count + 1

  sample.connect(callback)(0)

  sample.connect(functools.partial(equal, sys.getrecursionlimit()))

@test
def chain():
  expect(1)

  sample = event.event()

  next = sample
  for _ in range(sys.getrecursionlimit()):
    prev = next
    next = event.event()

    prev.connect(next)
    next.connect(lambda count: count + 1)

  sample(0)

  next.connect(functools.partial(equal, sys.getrecursionlimit()))

@test
def propagateEvent():
  expect(1)

  sample = event.event()
  for _ in range(sys.getrecursionlimit()):
    sample.connect(lambda count: event.event()(count + 1))

  sample(0)

  sample.connect(functools.partial(equal, sys.getrecursionlimit()))

@test
@event.continuate
def continuate():
  expect(1)

  count = 0
  for _ in range(sys.getrecursionlimit()):
    yield event.event()('Call')

    count += 1

  equal(sys.getrecursionlimit(), count)
