#!/usr/bin/env python

import gc, re, sys
from StringIO import StringIO
from testify import *
from untwisted import event

# Throw

stderr = sys.stderr
sys.stderr = StringIO()

event.event().throw(Exception('Throw'))

stderr, sys.stderr = sys.stderr, stderr

ok(re.match('''(?:  File ".+", line \d+, in .+
    .+
)+  File "%s", line \d+, in <module>
    event.event\(\).throw\(Exception\('Throw'\)\)
  File ".+", line \d+, in .+
    .+
Traceback \(most recent call last\):
(?:  File ".+", line \d+, in .+
    .+
)+Exception: Throw
''' % re.escape(__file__), stderr.getvalue()), stderr.getvalue())

# Raise

# Don't use decorator to avoid any assignment
def callback(*args, **kwds):
  raise Exception('Raise')

stderr = sys.stderr
sys.stderr = StringIO()

event.event()('Raise').connect(callback)

gc.collect()

stderr, sys.stderr = sys.stderr, stderr

ok(re.match('''(?:  File ".+", line \d+, in .+
    .+
)+Traceback \(most recent call last\):
(?:  File ".+", line \d+, in .+
    .+
)+  File "%s", line \d+, in callback
    raise Exception\('Raise'\)
Exception: Raise
''' % re.escape(__file__), stderr.getvalue()), stderr.getvalue())

# Throw type, value, traceback

try:
  raise Exception('Throw type, value, traceback')

except:
  pass

stderr = sys.stderr
sys.stderr = StringIO()

event.event().throw(*sys.exc_info())

stderr, sys.stderr = sys.stderr, stderr

ok(re.match('''(?:  File ".+", line \d+, in .+
    .+
)+Traceback \(most recent call last\):
  File "%s", line \d+, in <module>
    raise Exception\('Throw type, value, traceback'\)
Exception: Throw type, value, traceback
''' % re.escape(__file__), stderr.getvalue()), stderr.getvalue())

# Throw no argument

try:
  raise Exception('Throw no argument')

except:
  pass

stderr = sys.stderr
sys.stderr = StringIO()

event.event().throw()

stderr, sys.stderr = sys.stderr, stderr

ok(re.match('''(?:  File ".+", line \d+, in .+
    .+
)+Traceback \(most recent call last\):
  File "%s", line \d+, in <module>
    raise Exception\('Throw no argument'\)
Exception: Throw no argument
''' % re.escape(__file__), stderr.getvalue()), stderr.getvalue())

# Throw then raise

# Don't use decorator to avoid any assignment
class callback:

  @staticmethod
  def throw(*args, **kwds):
    raise Exception('Expect')

stderr = sys.stderr
sys.stderr = StringIO()

event.event().throw(Exception('Handle')).connect(callback)

stderr, sys.stderr = sys.stderr, stderr

ok(re.match('''(?:  File ".+", line \d+, in .+
    .+
)+Traceback \(most recent call last\):
(?:  File ".+", line \d+, in .+
    .+
)+  File "%s", line \d+, in throw
    raise Exception\('Expect'\)
Exception: Expect
''' % re.escape(__file__), stderr.getvalue()), stderr.getvalue())
